services:
  postgres:
    image: postgres
    volumes:
      - ./init_bank_db.sql:/docker-entrypoint-initdb.d/init_bank_db.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"