ktor:
  application:
    modules:
      - com.challenge.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:postgresql://localhost:5432/bank"
  user: "postgres"
  password: "postgres"
